### PR TITLE
11th of December changes

### PR DESCRIPTION
**Pull request by Maxuss**
Since the 11th of December, ChatGPT now has an extra cloudflare protection. This pull request will implement an authentication backend a single embedded browser-based authentication method.

More authentication methods will be added later

### CODE REVIEW

**Comment by Maxuss** [comment]
Due to the fact that ChatGPT servers are pretty much dead right now, I can't really test the implementation. We will have to wait.

**Comment by Maxuss** [comment]
It seems that both fantoccini and rust_headless_chrome are being detected by Cloudflare. I will look more in depth at how puppeteer can sneak behind it. Current workaround (the .js scripts in `./src/auth/simple/evade/`) does not seem to work.

**Comment by Kixunil** [comment]
Wouldn't it be possible to just copy all the cookies from browser or something along those lines?

**Comment by Maxuss** [comment]
> Wouldn't it be possible to just copy all the cookies from browser or something along those lines?

That would require users to login to chatgpt manually every 2 hours, and it is not always possible. The API client would also need to use the same user agent as the browser used to login, which is also impossible without extra hassle on user side. I could extract cookies and user agent from the browser cache but that poses as a security risk, and I have no idea how you would operate a browser on a server.

I am looking for other ways to login to ChatGPT. Projects like https://github.com/transitive-bullshit/chatgpt-api or https://github.com/acheong08/ChatGPT use puppeteer or selenium respectively, which I couldn't really get to work with Rust (maybe I am doing something the wrong way though). Interesting thing I've found is https://github.com/PawanOsman/ChatGPT.Net but it uses a closed-source proxy, so I can not guarantee 100% security when using it. Moreover, I am not even sure I can get the permission to use this proxy.

Another solution could be hosting a local server from a separate language (e.g. https://github.com/ChatGPT-Hackers/ChatGPT-API-server), and connecting to it, but I haven't really looked into that, and I want my API to work out of the box.

**Comment by Maxuss** [comment]
I have found another selenium frontend, built on top of fantoccini: https://github.com/stevepryde/thirtyfour, but I have yet to test it.

**Comment by Kixunil** [comment]
I would happily incur that extra hassle to not have to run the browser or other weird hacks.

**Comment by Maxuss** [comment]
I'll add that as an alternative/placeholder login method then

**Comment by Kixunil** [comment]
Thanks!

**Comment by CPlusPatch** [comment]
Can't wait for this to work again! Great work @Maxuss !

**Comment by Maxuss** [comment]
Thanks, I am trying to find methods other than browser one when I have free time. The cloudflare cookie seems to be fully patched, I can't get it to work, even after copying all cookies from browser + user agent + same ip. Hopefully OpenAI releases an actual API soon

**Comment by MavenRain** [comment]
> Thanks, I am trying to find methods other than browser one when I have free time. The cloudflare cookie seems to be fully patched, I can't get it to work, even after copying all cookies from browser + user agent + same ip. Hopefully OpenAI releases an actual API soon

You mean this?  https://github.com/64bit/async-openai

**Comment by Maxuss** [comment]
> You mean this? https://github.com/64bit/async-openai

Yeah, I think OpenAI will release a REST API as they did with DALL-E 2 and GPT-3 models at some point.

**Comment by Maxuss** [comment]
Apparently we can finally use official API
https://github.com/transitive-bullshit/chatgpt-api/

This is great, I will work on it when I have time next week

**Comment by Maxuss** [comment]
Official API is finally here :tada: 

https://openai.com/blog/introducing-chatgpt-and-whisper-apis

**Review by RoryShively — APPROVED** [review]

**Comment by Maxuss** [comment]
Pretty much only docs and some more testing left, will be able to finish it tomorrow

**Pull request merged**
